version: '3'

services:
  hive:
    build: hive_project/docker
    tty: true
    ports:
      - '7990:8000'
    volumes:
      - './:/app/'
    working_dir: '/app'
    privileged: true
    environment:
      - DJANGO_SETTINGS_MODULE=hive_project.settings
    links:
      - pgsql

  pgsql:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5428:5432"
