# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hive', '00010_'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO hive_entityfieldtype(id, name, class_name, sql_type) VALUES(%s,%s,%s,%s)",[6, 'money', 'MoneyFieldType', 'int']),
            ],
            reverse_sql=[
                ("DELETE FROM hive_entityfieldtype where id=%s;", [6])
            ]
        ),
    ]
