# Generated by Django 4.1.7 on 2023-04-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'hive_entityfieldtype',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fields', models.JSONField(default=list)),
                ('identity', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_keys', models.JSONField(default=list, max_length=50, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.entitytype')),
            ],
        ),
    ]
