# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO hive_entitytype(id, name, class_name, file_name) VALUES(%s,%s,%s, %s)",
                 [1, 'History', 'HistoryStorage', 'history_storage']),
                ("INSERT INTO hive_entitytype(id, name, class_name, file_name) VALUES(%s,%s,%s, %s)",
                 [2, 'Update', 'UpdateStorage', 'update_storage'])
            ],
            reverse_sql=[
                ("DELETE FROM hive_entitytype where id=%s;", [1]),
                ("DELETE FROM hive_entitytype where id=%s;", [2])
            ]
        ),
    ]
