# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hive', '0003_'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO hive_entityfieldtype(id, name, class_name, file_name) VALUES(%s,%s,%s,%s)",
                 [1, 'int', 'IntEntityFieldType', 'int_entity_field_type']),
                ("INSERT INTO hive_entityfieldtype(id, name, class_name, file_name) VALUES(%s,%s,%s,%s)",
                 [2, 'str', 'StringEntityFieldType', 'string_entity_field_type'])
            ],
            reverse_sql=[
                ("DELETE FROM hive_entityfieldtype where id=%s;", [1]),
                ("DELETE FROM hive_entityfieldtype where id=%s;", [2])
            ]
        ),
    ]
