# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0006_'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO hive_entityfieldtype(id, name, class_name, file_name) VALUES(%s,%s,%s,%s)",
                 [4, 'float', 'FloatEntityFieldType', 'float_entity_field_type'])
            ],
            reverse_sql=[
                ("DELETE FROM hive_entityfieldtype where id=%s;", [4])
            ]
        ),
    ]
