# Generated by Django 4.1.7 on 2023-05-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0007_'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityFieldType',
        ),
    ]
