# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('hive', '0008_delete_entityfieldtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=255, unique=True)),
                ('sql_type', models.CharField(default='', max_length=255, unique=False)),
            ],
            options={
                'db_table': 'hive_entityfieldtype',
            },
        ),
    ]
